app:
  name: poc_hyde_feed_recommendation
  timezone: UTC

llm:
  # model_name: gemini-2.5-flash
  model_name: gemini-3.1-flash-lite-preview
  embedding_model : gemini-embedding-001
  max_output_tokens: 2048
  temperature: 0.2
  slow_time: 30
  output_dim: 768

hyde:
  history_threshold: 5
  recent_k: 5
  feed_text_max_chars: 240
  retry_limit: 2
  prompt_version: v2

bigquery:
  project: poc-piloturl-nonprod
  dataset: mock_feed_recommendation
  tables:
    students: silver_students
    interactions: silver_user_community_relation
    feeds: silver_feed_community
    l20_interaction: gold_agg_l20_user_interaction

cloudstorage:
  bucket: hyde-datalake-feed-recommend
